name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [main]
  
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Info 
        run: |
          echo "version=$(awk '/version /' init.rb | awk -F"'" '$0=$2')" >> $GITHUB_OUTPUT
        id: info
      - name: Pack Plugin
        run: |
          cd ${{ github.workspace }}
          git submodule update --init --recursive
          mkdir -p ./deploy/onlyoffice_redmine
          rsync -av --exclude='deploy' ./ ./deploy/onlyoffice_redmine
          cd ./deploy/onlyoffice_redmine
          rm -rf ./.github/
          rm -rf ./.git/
          rm ./.gitmodules ./Gemfile ./Gemfile.lock
          mv ./Gemfile.prod ./Gemfile
          cd ./assets/document-templates
          rm .git
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: onlyoffice_redmine
          path: deploy