name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [main]
  
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Info 
        run: |
          echo "::set-output name=version::$(awk '/version /' init.rb | awk -F"'" '$0=$2')"
        id: info
      - name: Pack Plugin
        run: |
          cd ${{ github.workspace }}
          git submodule update --init --recursive
          mkdir -p ./deploy/onlyoffice-redmine
          rsync -av --exclude='deploy' ./ ./deploy/onlyoffice-redmine
          cd ./deploy/onlyoffice-redmine
          rm -rf ./.github/
          rm -rf ./.git/
          rm ./.gitmodules
          cd ./assets/document-templates
          rm -r az-Latn-AZ bg-BG cs-CZ el-GR en-GB ko-KR lv-LV nl-NL pl-PL sk-SK sv-SE tr-TR uk-UA vi-VN
          rm .git
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: onlyoffice-redmine
          path: deploy