name: Audit

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1

    - name: Update Submodules
      run: make submodule

    - name: Install Dependencies
      run: make install

    - name: Check for Type Safety
      run: make type

    - name: Lint for the Style
      run: make lint

    - name: Run Tests
      run: make test
