name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Update Submodules
      run: make submodule

    - name: Build Plugin
      run: make build

    - name: Create Artifact
      run: make artifact

    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        version="v$(make version)"
        gh release create "$version" --notes "$(make notes)"
        gh release upload "$version" onlyoffice_redmine.tar.zst
